# The URL the site will be built for
base_url = "https://cosmietta.is-a.dev"

# Theme
theme = "linkita"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# The default language.
# "en" is for English.
default_language = "en"

# The default author for pages.
# See "extra.profiles".
author = "cosmietta"

# The site title.
# Will be in all page titles.
title = "Cosmietta"

# The site description.
# Used in feeds by default.
description = "Personal Website"

# Automatically generate a feed.
# Default value: false
generate_feeds = true

# The filenames to use for the feeds.
# e.g. ["rss.xml"]
feed_filenames = ["atom.xml"]

taxonomies = [
  { name = "tags", feed = true, paginate_by = 5 },
  { name = "authors", feed = true, paginate_by = 5 },
]


# Build a search index from the pages and section content
# for "default_language".
# build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
error_on_missing_highlight = false
highlight_theme = "boron"
render_emoji = true
smart_punctuation = false
definition_list = true
bottom_footnotes = true

[extra]
# Put all your custom variables here
math = false
mermaid = false
comment = false
title_separator = " | "
header_menu_name = "sample_header"
page_info = [{ when="date" }, { when="date_updated", prepend="(", append=")" }, { when="reading_time" }]
page_info_on_paginator = [{ when="date" }, { when="reading_time" }, { when="authors" }]
use_cdn = false
relative_urls = false
urls_to_index_html = false
disable_default_favicon = false
page_summary_on_paginator = false
invert_page_navigation = false

[extra.style]
bg_color = ""
bg_dark_color = ""
header_blur = true
header_color = ""
header_dark_color = ""


[extra.menus]
sample_header = [
  { url = "$BASE_URL/", name = "Home", names_i18n = "common_home" },
  { url = "$BASE_URL/projects/", name = "Projects", names_i18n = "common_projects" },
  { url = "$BASE_URL/blog/", name = "Blog", names_i18n = "common_blog" },
]

[extra.profiles]

# Linkita's profile
[extra.profiles.cosmietta]
avatar_url = "icons/avatar.png"
avatar_invert = false
# avatar_alt = "Default alt text"
 name = "Cosmietta"
# bio = "Default bio"
social = [
  { name = "instagram", url = "https://www.instagram.com/rizqilayl" },
  { name = "github", url = "https://github.com/Cosmietta" },
  { name = "email", url = "mailto:rizqilayl7@gmail.com" },
  { name = "steam", url = "https://steamcommunity.com/id/Cosmietta" },
   
]

[extra.footer]
since = 2025
license_url = "https://creativecommons.org/licenses/by-sa/4.0/"
copyright = "&copy; $YEAR Cosmietta &vert; [CC BY-SA 4.0]($LICENSE_URL)"